spring:
  datasource:
    url: jdbc:h2:mem:petsDb
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.show-sql: true
    spring.jpa.hibernate.ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true